sudo: false
language: scala

jdk:
  - oraclejdk8

script:
  - sbt +test
  - sbt +publishLocal

cache:
  directories:
    - $HOME/.ivy2/cache
    
before_cache:
  # Delete all ivydata files
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm

